### ISSUE TITLE
Point people to the new project reflection template

### ISSUE THREAD

**Issue by dluetger** [18F/delivery-assurance#134]
### A description of the work
Create links and references to point folks to the new project reflection template (created in #83 )so it can be tested. This includes the Project Leads handbook page and the #project-reflections Slack Channel, but also take a look and see what other references to the old template are out there so they can be updated.

### Point of contact on this issue
@dluetger @katefisher808 

### Reproduction steps (if necessary)
-

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ X] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?
~4 hours, mostly to find other reference points

### Acceptance Criteria

- [ ] The project reflection template is linked from the Project Leads handbook page
- [ ] The new template is linked from #project-reflections in Slack
- [ ] Other references are researched and edited
-

**Comment by katefisher808** [comment]
I shared some draft language for the [Leading a Project](https://handbook.tts.gsa.gov/18f/projects-partners/leading-projects/) page on slack for review before pushing the change on the handbook.
Draft language found here:
https://gsa.enterprise.slack.com/files/T025AQGAN/F0539LMJXJN

**Comment by MelissaBraxton** [comment]
Hey there, @katefisher808  - Is there a reason the revisions no longer mention asking for a facilitator? It might be good to at least make sure it's clear that the recommendation is that the reflection be facilitated by someone other than the project lead. 

Also, the toolkit link being first in the list of references and the fact that it goes to a Google folder with 4 things in it is a bit disorienting. Consider removing the toolkit link, since you point them to the specific things in the toolkit they should pay attention to later in that same sentence.

**Comment by katefisher808** [comment]
Good points! Thank you @MelissaBraxton - I'll update the links.

Regarding the thinking around removing the specific guidance re: facilitator is to differentiate the Handbook steps from the Facilitation Guide steps. That was the one piece of information that lived in both places, and I thought the Facilitation Guide seemed to do it a little better (it had the 'why you should have a separate facilitator' and 'what other roles are involved' along with the steps for requesting a facilitator)

**Comment by MelissaBraxton** [comment]
I think it'd be good to add it here too. Putting my project lead hat on, I might otherwise be inclined to schedule the reflection, and then only open the guide a day or two before as I'm getting ready to facilitate. #18f-help-wanted is the new place folks would ask for a facilitator though, so we should update that!

**Comment by katefisher808** [comment]
Updated language in PR here! https://github.com/18F/handbook/pull/3553
It's waiting on one review in the Handbook github.

**Comment by katefisher808** [comment]
I'm going to mark this one done since it's in the handbook github flow now for final review + merge.
