### ISSUE TITLE
Establish the DA Team Issue labels

### ISSUE THREAD

**Issue by colinmurphy01** [18F/delivery-assurance#73]
### A description of the work
As a DA Team member and executive sponsor, it'd be helpful to have labels applied to our issues in order to easily determine how to prioritize them and what's the right work for me, now.

Consideration:
All connected repos manage their own labels for issues. If we wanted to have a label supported in every repo/issue - it would have to be applied in every repo. There might be a way to do sync them automatically?

### Point of contact on this issue
@colinmurphy01 @kfoley-18F 

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [x] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [x] Yes
- [ ] No

How much time do you anticipate this work taking?
1 week

### Acceptance Criteria

Strategy considers
- [ ] A LT sponsor can use labels to accurately and efficiently prioritize work
- [ ] A DA Team member can use labels to assess fit for their skills (and bandwidth?)
- [ ] A PO of a connected repo can add the label to their ticket and have it reflected in the shared project board

**Comment by kfoley-18F** [comment]
I'm open to that, as long as there are ways to code for "everyone" or "no discipline/generic" options.

**Comment by colinmurphy01** [comment]
🍿

**Comment by jduss4** [comment]
The new "skills needed" field has been applied to this project board.  You can view / edit it here:  https://github.com/orgs/18F/projects/41/settings/fields/38007659

I tried to keep the descriptions brief, because they show up in the dropdown, but hopefully they communicate their points!

The skills are:

```
DA : any
DA : a11y
DA : content
DA : design
DA : dev
DA : frontend
DA : PM
DA : research
```

We decided to make "frontend" unique, because there are lots of non-dev or non-dev heavy frontend tasks. Additionally, research is its own thing to capture unique needs for research skills like user research. That tag is not intended for tasks that anybody likely has the ability to do, such as desk research.
