### ISSUE TITLE
Create visuals for 18F aavatars that include representations of people with disabilities

### ISSUE THREAD

**Issue by bpdesigns** [18F/delivery-assurance#91]
### A description of the work
update 18F avatars to include representation of the American public who have disabilities.  

**references**
[gov.uk personas](https://alphagov.github.io/accessibility-personas/) 
[Microsoft inclusive design guide](https://inclusive.microsoft.design/tools-and-activities/Inclusive101Guidebook.pdf)
[wc3 personas](https://www.w3.org/TR/coga-usable/#persona) + [mapping personas to design patterns](https://www.w3.org/TR/coga-usable/#appendix-mapping-user-needs-personas-and-patterns)

### Point of contact on this issue
@bpdesigns 
**Billable?**
- [ ] Yes
- [x] No

If yes, tock code:

**Skills needed**

- [x] Any human
- [x] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [x] No

How much time do you anticipate this work taking?
- 2 weeks

### Acceptance Criteria
 - [x]  We have researched and documented considerations for moving forward with aavatars that include representations of people with disabilities. 

ex: As an 18F staff member who is going on parental leave, I can navigate to my
latest Tock reporting period and choose billing line #1810 by filtering by
number or "extended OOO"

**Comment by bpdesigns** [comment]
[gdrive](https://drive.google.com/drive/search?q=%22three%20horizons%22)

and @cmajel for awareness and possibly newer info on this

**Comment by cmajel** [comment]
@katefisher808 [The 18F brand site's icon page](https://brand.18f.gov/icons/) has some more detail on where these illustrations come from.

I'll note that the creator of this library has since created another library ([open peeps)](https://www.openpeeps.com/) that includes disability representation and is generally more robust. It includes different views (full body, sitting, standing) and includes more detail, which may be useful in certain contexts. 

(As the person who worked on the 18F avatar set, I'd be interested in seeing this investigated more!)

**Comment by melchoyce** [comment]
@katefisher808 want to collaborate on this one?

**Comment by katefisher808** [comment]
With my new apple-stylus-pencil... I was just waiting for you to ask! yes!

**Comment by bpdesigns** [comment]
Added some more references from WC3

**Comment by melchoyce** [comment]
Hey @bpdesigns, were those W3C reference meant for #92?

**Comment by bpdesigns** [comment]
@melchoyce I was thinking the wc3 references might be useful for this and #92. Thanks for the catch. Looks like I forgot to click "update comment" on #92. I'll update that now.

**Comment by katefisher808** [comment]
Update on progress from the week from @melchoyce and me:
- We set up a [short discovery doc](https://docs.google.com/document/d/1EzyrBZwWfR4ZgoRTtwqXF2Hx-IGmDBTYOUokQhhG4VU/edit#) that outlined context, questions, and conducted two short conversations to learn more
- We outlined some initial insights from the conversations
- We defined some next steps to move this ticket forward which include aligning on the persona ticket, chatting briefly with Igor and Aviva

Next week, we plan to have those additional conversations, define 'done' for this ticket, and suggest new tickets that build on this work

**Comment by MelissaBraxton** [comment]
Checking in on this in prep for the end of the week, are we on track to move this to done and document any follow on work as new issues before the weekend?

**Comment by katefisher808** [comment]
We'll be updating this with our recommendations and next steps today! Thanks Melissa.

**Comment by katefisher808** [comment]
@bpdesigns and team,
Sharing the [summary from our research](https://docs.google.com/presentation/d/1mkzDrt1uIBtsWA4qrXJ4HY2Ul5C-d5ScuQ1p0XqKEqU/edit#slide=id.g5ecdbbee9e_0_0) on this issue. We are hoping to share this deck with you and the DA team for a discussion early next week in one of the standing DA meetings. From there, we'll define next steps / new issues.

**Comment by MelissaBraxton** [comment]
Thanks for your awesome work on this, @melchoyce and @katefisher808! Let's call this issue done. I revised the acceptance criteria to be just this initial landscape analysis. But, we'll need new issues for carrying it forward. Given [your research](https://docs.google.com/presentation/d/1mkzDrt1uIBtsWA4qrXJ4HY2Ul5C-d5ScuQ1p0XqKEqU/edit#slide=id.g5ecdbbee9e_0_0), I see two next steps:
 
1.  Expand our library to include a few additional 18F Aavatars that include representations of people with disabilities (slide 14 in your presentation) - Can you two please make a new issue for this?
2. Share your research with the @quarterback so that he can weigh on your other ideas in your deck re: using a new avatar library (slide 15) re revisiting our collective 18F graphics library (slide 16) - I will create a new issue for this.

**Comment by MelissaBraxton** [comment]
@melchoyce and @katefisher808 - I made #138 and #139 to capture next steps. I think we can close this one out.
